config/routes.rb
Lilliputian::Application.routes.draw do
    root "posts#index"

    get "/about" => "pages#about"

    # Auth
    resources :sessions
    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"

    # Posts
    resources :posts

    # Post archive
    get "/archive" => "posts#archive"
    get "/archive/:year" => "posts#archive"
    get "/archive/:year/:month" => "posts#archive"

    # Tags
    resources :tags
    resources :post_tags
end

app/models/post.rb
class Post < ActiveRecord::Base
    self.per_page = 10
    
    def to_param
        "#{slug}-#{id}"
    end
    
    belongs_to :user
    has_many :post_tags, :dependent => :delete_all
    has_many :tags, :through => :post_tags

    validates_presence_of :user_id
    validates :title, presence: true, length: { minimum: 1 }
    validates :content, presence: true, length: { minimum: 5 }
    validates :slug, presence: true, uniqueness: true, length: { minimum: 1 }
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
    validates_uniqueness_of :post, :scope => :tag
    belongs_to :post
    belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    def to_param
        tag
    end

    before_validation :downcase_and_underscores

    has_many :post_tags, :dependent => :delete_all
    has_many :posts, :through => :post_tags
    validates :tag, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }

    private

    def downcase_and_underscores
        self.tag = self.tag.downcase.gsub(/\s+/, "_")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
    has_secure_password

    before_validation :downcase_email
    validates_presence_of :password, :on => :create
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates_uniqueness_of :email

    private
    def downcase_email
        self.email = self.email.downcase if self.email.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_login
      unless current_user
        redirect_to root_url, :notice => "You must be logged in to access this page."
        return false
      end
    end

    def flash_class(level)
        case level
        when :notice then "info"
        when :error then "error"
        when :alert then "warning"
        end
    end

    helper_method :current_user, :flash_class, :require_login
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
end

app/controllers/post_tags_controller.rb
class PostTagsController < ApplicationController
    before_filter :require_login, :only => [:create, :destroy]

    def create
        post = Post.find(params[:post_id])
        tag = Tag.find(params[:tag_id])

        begin
            post.tags << tag
        rescue ActiveRecord::RecordInvalid
            redirect_to post, :notice => "Tag already added."
        else
            redirect_to post, :notice => "Tag added to post." 
        end
    end

    def destroy
        post_tag = PostTag.find(params[:id])
        post = post_tag.post
        post_tag.destroy

        redirect_to post, :notice => "Tag removed from post."
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_filter :require_login, :only => [:new, :edit, :update, :create, :destroy]

    def index
        @posts = Post.order("created_at DESC").page(params[:page])
    end

    def archive
        @posts = Post.find(:all, :order => "created_at DESC").group_by { |post| post.created_at.beginning_of_month }
    end

    def new
        if not current_user
            redirect_to login_url, :notice => "You must login to create posts."
        else
            @post = Post.new
        end
    end

    def show
        @post = Post.find(get_id(params[:id]))
    end

    def edit
        @post = Post.find(get_id(params[:id]))
        render :new
    end

    def create
        @post = Post.new post_params
        @post.user = current_user
        @post.slug = @post.title.to_slug

        if @post.save
            redirect_to @post, :notice => "Article created."
        else
            render :new
        end
    end

    def update
        @post = Post.find(get_id(params[:id]))

        if @post.update_attributes(post_params)
            redirect_to @post, :notice => "Post updated."
        else
            render :new
        end
    end

    def destroy
        @post = Post.find(get_id(params[:id]))
        @post.delete

        redirect_to root_url, :notice => "Post removed."
    end

    private
    def post_params
        params.require(:post).permit(:title, :content)
    end

    def get_id(str)
        str.split("-")[-1]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_email(params[:email])
    
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_url, :notice => "You have been logged in."
        else
            flash.now.alert = "Invalid email or password!"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, :notice => "You have been logged out."
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_filter :require_login, :only => [:create, :destroy]

    def index
        @tags = Tag.all
        @tag = Tag.new
    end

    def show
        @tag = Tag.find_by_tag params[:id]
        @posts = @tag.posts.order("created_at DESC").page(params[:page])

        render "posts/index"
    end

    def create
        @tag = Tag.new tag_params 

        if @tag.save
            redirect_to tags_path, :notice => "'#{@tag.tag}' added."
        else
            @tags = Tag.all
            render :index
        end
    end

    def destroy
        @tag = Tag.find_by_tag params[:id]
        @tag.delete

        redirect_to tags_path, :notice => "Tag removed."
    end

    private
    def tag_params
        params.require(:tag).permit(:tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_markdown(str)
        markdown = Redcarpet::Markdown.new(
            Redcarpet::Render::HTML,
            :autolink => true, 
            :space_after_headers => true, 
            :no_intra_emphasis => true
        ).render(str).html_safe
    end

    def title
        "Lilliputian"
    end

    def author
        "The Author"
    end

    def sub_title
        "sub title"
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_alert.html.erb
<% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
        <div class="alert alert-<%= flash_class(level) %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :p, flash[level] %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width"> 
        <meta name="description" content="<%= title %> - <%= content_for?(:description) ? yield(:description) : "A blog." %>">
        <meta name="keywords" content="">
        <meta name="author" content="<%= author %>">
        <title><%= title %> - <%= content_for?(:title) ? yield(:title) : "No title" %></title>

        <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1>
                        <%= title %>
                        <small>
                            <%= sub_title %>
                        </small>
                    </h1>
                    <ul class="list-inline"> 
                        <li><%= link_to "home", root_path %></li>
                        <li><%= link_to "archive", archive_path %></li>
                        <li><%= link_to "tags", tags_path %></li>
                        <li><%= link_to "about", about_path %></li>

                        <% if !current_user.nil? %>
                            <li><%= link_to("new post", { controller: "posts", action: "new" }) %></li>
                            <li><%= link_to("sign out", logout_path) %></li>
                        <% end %>
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <%= render "layouts/alert" %>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <%= yield %>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <hr>
                    <footer>
                    &copy; 2014 <%= author %>
                    <span class="pull-right text-muted">This blog uses <%= link_to "Lilliputian", "http://www.bitbucket.org/argelius/lilliputian" %>, a tiny blog application written in Rails.</span>
                    </footer>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/pages/about.html.erb
<%
    content_for(:title, "About")
    content_for(:description, "Description of the author")
%>

<h3>About me</h3>

<p>Some text</p>

app/views/posts/archive.html.erb
<%
    content_for(:title, "Blog archive")
    content_for(:description, "Blog archive")
%>

<h3>Blog archive</h3>
<% @posts.each do |month, posts| %>
    <h4><%= "#{month.strftime('%B %Y')} (#{posts.count}):" %></h4>
    <ul>
        <% for post in posts %>
            <li><%= link_to post.title, post %></li>
    <% end %>
    </ul>
<% end %>

app/views/posts/index.html.erb
<%
    content_for(:title, "Home")
    content_for(:description, "Home")
%>

<% if @posts.count == 0 %>
    <% if @tag %>
    <p>No posts with this tag.</p>
    <% else %>
        <p>No posts published yet.</p>
    <% end %>
<% else %>
    <% if @tag %>
        <h4>Posts tagged with '<%= @tag.tag %>'</h4>
    <% else %>
        <h4>Latest posts</h4>
    <% end %>

    <% @posts.each do |p| %>
    <div class="row">
    <div class="col-md-4 col-md-2-offset text-right text-sans">
        <%= p.created_at.to_formatted_s(:short) %>
    </div>
    <div class="col-md-6">
        <strong><%= link_to p.title, p %></strong>
        <p><%= truncate(strip_tags(render_markdown(p.content)).html_safe, length: 250, :escape => false) %></p>
    </div>
</div>
<% end %>
<% end %>

<%= will_paginate @posts, :page_links => false %>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Add blog post</h1>
        <%= form_for @post do |f| %>
            <% messages = @post.errors.messages %>
            <div class="form-group <% if messages.has_key? :title %>has-error<% end %>">
                <%= f.label :title %>
                <%= f.text_field :title, :class => "form-control" %>
                <% if messages.has_key? :title %>
                    <span class="help-block">
                        <ul class="list-unstyled">
                            <% messages[:title].each do |m| %>
                                <li>Title <%= m %></li>
                            <% end %>
                        </ul>
                    </span>
                <% end %>
            </div>
            <div class="form-group <% if messages.has_key? :content %>has-error<% end %>">
                <%= f.label :content %>
                <%= f.text_area :content, :rows => 15, :class => "form-control" %>
                <% if messages.has_key? :content %>
                    <span class="help-block">
                        <ul class="list-unstyled">
                            <% messages[:content].each do |m| %>
                                <li>Content <%= m %></li>
                            <% end %>
                        </ul>
                    </span>
                <% end %>
            </div>
            <%= f.submit("Publish", :class => "btn btn-default") %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<%
    content_for(:title, @post.title)
content_for(:description, "#{@post.title} - #{@post.tags.map(&:tag).join(", ")}")
%>

<% if current_user %>
    <div class="row">
    <div class="col-md-6">
        <ul class="list-inline">
            <li><%= link_to "Delete", @post, :method => :delete, :confirm => "Are you sure you want to remove the post?" %></li>
            <li><%= link_to "Edit", edit_post_path(@post) %></li>
        </ul>
    </div>
    <div class="col-md-4 col-md-offset-2">
        <%= form_tag post_tags_path(:post_id => @post.id) do %>
            <div class="form-group">
                <%= select_tag :tag_id, 
                    options_from_collection_for_select(Tag.all, "id", "tag"), 
                    :class => "form-control",
                    :prompt => "Add tag" %>
        </div>
    <% end %>
    </div>
</div>
<% end %>

<div class="row">
    <div class="col-md-12">
        <article>
            <header>
                <h2><%= @post.title %></h2>
                Published
                <time><%= @post.created_at.to_formatted_s(:short) %></time>
                by <%= mail_to @post.user.email, @post.user.name %>
            </header>
            <hr>
            <%= render_markdown(@post.content) %>
            <% if @post.tags.count > 0 %>
                <br />
                <span class="pull-right">
                    This post has been tagged with <%= @post.tags.map{|t| link_to t.tag, t}.to_sentence.html_safe %>.
                </span>
            <% end %>
        </article>
    </div>
</div>

app/views/tags/index.html.erb
<%
    content_for(:title, "Tags")
    content_for(:description, "Tag cloud")
%>

<h3>Tags</h3>

<% if @tags.count == 0 %>
    <p>No tags added.</p>
<% else %>
<ul class="list-inline">
    <% @tags.each do |tag| %>
        <li>
            <%= link_to tag.tag, tag %>
            <% if current_user %>
                [<%= link_to "-", tag, :method=>:delete  %>]
            <% end %>
        </li>
    <% end %>
</ul>
<% end %>

<% if !current_user.nil? %>
    <hr>
    <h5>Add new tag</h5>
    <%= form_for @tag do |f| %>
        <% messages = @tag.errors.messages %>
        <div class="form-group <% if messages.has_key? :tag %>has-error<% end %>">
            <%= f.text_field :tag, :class => "form-control", :autocomplete => :off %> 
            <% if messages.has_key? :tag %>
                <span class="help-block">
                    <ul class="list-unstyled">
                        <% messages[:tag].each do |m| %>
                            <li>Tag <%= m %></li>
                        <% end %>
                    </ul>
                </span>
            <% end %>
        </div> 
        <%= f.submit("Add tag", :class => "btn btn-default") %>
    <% end %>
<% end %>